"""empty message

Revision ID: 07da236a3643
Revises: 50ac736e1c5d
Create Date: 2020-10-25 16:12:11.292527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07da236a3643'
down_revision = '50ac736e1c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel', 'image')
    # ### end Alembic commands ###
