"""empty message

Revision ID: 50ac736e1c5d
Revises: e38f42fede75
Create Date: 2020-10-24 17:34:03.824708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ac736e1c5d'
down_revision = 'e38f42fede75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_at')
    # ### end Alembic commands ###
