"""empty message

Revision ID: e38f42fede75
Revises: 183022ad92f1
Create Date: 2020-10-24 14:18:17.737794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38f42fede75'
down_revision = '183022ad92f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img_thumbnail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img_thumbnail')
    # ### end Alembic commands ###
